### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by GerryMandell** [prometheus-community/json_exporter#23]
**Operating systems reproduced in:**
OSX 10.14.1 (18B75)
ubuntu-18.04 (vagrant box)

**Go Version:**
`go version go1.11.4 darwin/amd64`

**Steps to Reproduce:**
1. Clone the repo `git clone https://github.com/kawamuray/prometheus-json-exporter.git`
2. Follow the readme instructions to build.
```
./gow get .
./gow build -o json_exporter .
```
3. Spin up the python simplehttpserver
`$ python -m SimpleHTTPServer 8000`
4. Execute `json_exporter`
`./json_exporter http://localhost:8000/example/data.json example/config.yml`

**Expected Results:**
```
$ ./json_exporter http://localhost:8000/example/data.json example/config.yml &
INFO[2016-02-08T22:44:38+09:00] metric registered;name:<example_global_value>
INFO[2016-02-08T22:44:38+09:00] metric registered;name:<example_value_active>
INFO[2016-02-08T22:44:38+09:00] metric registered;name:<example_value_count>
127.0.0.1 - - [08/Feb/2016 22:44:38] "GET /example/data.json HTTP/1.1" 200 -
```

**Actual Result:**
```
vagrant@vagrant:~/goworkspace/src/github.com/kawamuray/prometheus-json-exporter$ ./json_exporter http://localhost:8000/example/data.json example/config.yml
INFO[2019-01-31T22:10:00Z] metric registered;name:<example_global_value>
INFO[2019-01-31T22:10:00Z] metric registered;name:<example_value_active>
INFO[2019-01-31T22:10:00Z] metric registered;name:<example_value_count>
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/kawamuray/jsonpath.(*stack).pop(...)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/stack.go:126
github.com/kawamuray/jsonpath.evaluatePostFix(0xc00008d360, 0x3, 0x4, 0xc000137508, 0xc0001375c0, 0x0, 0x0, 0x0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/expression.go:348 +0x3c5f
github.com/kawamuray/jsonpath.(*exprBucket).evaluate(0xc0001377b8, 0xc000137938, 0x7b0543, 0xaaaaaaaaaaaaaaaa)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/eval.go:305 +0x43f
github.com/kawamuray/jsonpath.(*query).trySpillOver(0xc0000a1680)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/eval.go:162 +0x159
github.com/kawamuray/jsonpath.pathEndValue(0xc0000a1680, 0xc00012c5a0, 0xc0000f4d10, 0x8f4048)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/eval.go:282 +0x271
github.com/kawamuray/jsonpath.(*Eval).Iterate(0xc00012c5a0, 0xc000138e70, 0x1)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/eval.go:102 +0x375
github.com/kawamuray/jsonpath.(*Eval).Next(0xc00012c5a0, 0x15f, 0x200)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/jsonpath/eval.go:140 +0x3e
github.com/kawamuray/prometheus-json-exporter/jsonexporter.(*ValueScraper).forTargetValue(0xc000059ac0, 0xc00012a200, 0x15f, 0x200, 0xc000137bb0, 0xc000138390, 0x7e6df0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-json-exporter/jsonexporter/scraper.go:51 +0xc3
github.com/kawamuray/prometheus-json-exporter/jsonexporter.(*ObjectScraper).Scrape(0xc00000dc00, 0xc00012a200, 0x15f, 0x200, 0xc00000e0c0, 0x0, 0x0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-json-exporter/jsonexporter/scraper.go:149 +0x89
github.com/kawamuray/prometheus-json-exporter/jsonexporter.(*Collector).Collect(0xc000138390, 0xc00000e0c0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-json-exporter/jsonexporter/collector.go:77 +0xe5
github.com/kawamuray/prometheus-exporter-harness/harness.(*exporter).main(0xc00000e0b0, 0xc0000a4c60)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-exporter-harness/harness/exporter.go:71 +0x2ed
github.com/kawamuray/prometheus-exporter-harness/harness.(*exporter).main-fm(0xc0000a4c60)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-exporter-harness/harness/main.go:37 +0x34
github.com/urfave/cli.HandleAction(0x830380, 0xc0000594a0, 0xc0000a4c60, 0x0, 0x0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.(*App).Run(0xc0000ae540, 0xc00001e090, 0x3, 0x3, 0x0, 0x0)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/urfave/cli/app.go:268 +0x5b7
github.com/kawamuray/prometheus-exporter-harness/harness.Main(0xc00010f880)
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/build/src/github.com/kawamuray/prometheus-exporter-harness/harness/main.go:66 +0x5d
main.main()
	/home/vagrant/goworkspace/src/github.com/kawamuray/prometheus-json-exporter/json_exporter.go:12 +0xc7
```

**_NOTE_**: The extremely strange thing about this issue is, if I debug this in VSCode with the `launch.json` below the app works perfectly fine.
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceRoot}/json_exporter.go",
            "env": {},
            "args": ["http://localhost:8000/example/data.json", "example/config.yml"]
        }
    ]
}
```

**Comment by SuperQ** [comment]
Is this still an issue?

**Comment by rustycl0ck** [comment]
Closing due to inactivity. Please re-open if the problem still persists.
